server:
  port: 8080
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-8d939d076c03404b91b075d6dc7a976a
        model-name: qwen-plus-latest

#  open-ai:
#    chat-model:
#      base-url: http://langchain4j.dev/demo/openai/v1
#      api-key: demo
#      model-name: gpt-4o-mini
#      log-requests: true
#      log-responses: true


logging:
  level:
    com:
      qilin: debug
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aichat
